# Generated by Django 5.0.1 on 2024-02-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='name',
            field=models.CharField(default='no title', max_length=255, unique=True),
        ),
    ]
