# Generated by Django 5.0.1 on 2024-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='imgUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
