# Generated by Django 5.0.1 on 2024-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=70)),
                ('total_posts', models.IntegerField(default=0)),
                ('about', models.TextField(default='')),
            ],
        ),
    ]
