# Generated by Django 5.0.1 on 2024-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='total_subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
